version: "3"
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=password123
    links:
      - redis
      - mysql
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=bidapp
      - MYSQL_USER=bidapp
      - MYSQL_PASSWORD=password123
